---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  environment:
    SECRETVAL:
      from_secret: mykey
  commands:
    - echo $SECRETVAL

---
kind: secret
name: mykey
get:
  path: kv/test/mykey
  name: mykey
