---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: ubuntu:20.04
  environment:
    SECRETVAL:
      from_secret: mykey
  commands:
    - echo $SECRETVAL
    - echo TESTING

---
kind: secret
name: mykey
get:
  path: kv/data/test/data/mykey
  name: mykey
